### PR TITLE
Add pow(n), accessibility, and communication class functionality.

### PR DESCRIPTION
**Pull request by awilsoncs**
**Core Functionality**
Accessibility of states and communication classes are important characteristics of a Markov chain. I added functions to allow a user to easily calculate them.

**Performance Improvements**
I also added the ability to raise a Chain to a power without multiplying it with a vector. Using numpy's exponentiation, this greatly improved performance on large chains with high exponents. Exponentiation throughout the library has been updated to this method.

**Note**
As a note, with extremely high exponents (10**100), numpy will return increasingly inaccurate results. I've tested this with numpy alone and the same behavior occurs. Exponents in this range should not be common for MC applications, and the changes greatly increase the ceiling for which Pykov can accurately calculate.

### CODE REVIEW

**Comment by riccardoscalco** [comment]
Hi Aaron, thanks for the pr!
Please give me a couple of days to put my head in your code :)

**Comment by riccardoscalco** [comment]
Hi Aaron, sorry for the late merge.
Your pr is a  significant contribution to pykov, thanks.

Just a couple of questions:
1) The set of communication classes of the Markov chain is equal to the set of strongly connected components of the associated directed graph, am I right?
2) In the past I found myself to iterate p_t = p_t-1 * T in order to see the convergent distribution of a given initial state p_t=0. Actually the number of iterations depends on the transition matrix, do you expect that numpy's exponentiation can fulfill at tests like that where both the size of the chain and the exponent may be high?

**Comment by awilsoncs** [comment]
1) That's correct. There are some considerations for time-inhomogeneous chains, but Pykov isn't concerned with those.

2)  Theoretically, all of the same properties should hold since we're just offloading the multiplication. Increasing the chain size should not noticeably effect the error (the number of multiplications at an entry is what causes the floating-point error, and that only scales with the exponent). Larger MCs may require more iterations to find convergence, but we would have to be talking about MCs on the order of hundreds of thousands of nodes (maybe more) to see a problem.

**Comment by riccardoscalco** [comment]
Thanks Aaron, I'll update documentation as soon as possible.

**Pull request merged**
